language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
os:
  - linux
jobs:
  allow_failures:
    # We don't need to ignore failures once OPAM 2.0.7 is released.
    - env: OCAML_VERSION=4.10
